### ISSUE TITLE
N18125 producer reference time, correct reference 4.X.4.2.3

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Live#43]
please insert correct reference for producer reference time, mpeg document N18125 does not map back to a document about the updated producer reference time

**Comment by haudiobe** [comment]
Yes, the correct reference is N18416 which needs to produced over the weekend.

**Comment by RufaelDev** [comment]
@haudiobe can the document also be made available to DASH-IF ?
