### ISSUE TITLE
Requirements and Recommendation from DVB-DASH

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Live#46]
Note: Appropriate requirements from the DVB LL-DASH specification will be checked and may be added to the final version. Comments welcome.

**Comment by RufaelDev** [comment]
The low latency DASH spec at DASH-IF is not as well aligned with DVB DASH as mentioned in the spec text. 

**chunked fragments** and @availabilityTimeComplete=false : mandatory in DASH-F optional in DVB DASH
**ServiceDescription Element**  mandatory in both, but DVB also mandates the Scope element 

**PRFT MPD Element**  mandatory in DASH-IF but optional in DVB DASH 

**scoping urn to signal low latency content** defined in DVB but not in DASH-IF 

**supplemental/essential property for annotating ll adaptationset** available in DVB but not in DASH-IF 

**http chunked transfer encoding**     mandatory in DASH-IF but not in DVB 

**player behavior**        defined in DVB but not in DASH-IF (only limited)

**requirements for encoder/packager RT behavior** defined in DASH-IF but not in DVB

**inband prft (file format prft)**        used in DASH-IF but not in DVB  

It would be good consider aligning the two specifications as mentioned in the text. 
There are probably more differences/inconsistencies, but these were the ones that I found initially after going through the specifications. 
the two documents.

**Comment by haudiobe** [comment]
Check this finally until next week

**Comment by haudiobe** [comment]
chunked fragments and @availabilityTimeComplete=false : mandatory in DASH-F optional in DVB DASH

_In DASH-IF it is mandatory if you apply the low-latency Adaptation Set. I do not believe this contradicts. Anything to be done?_

ServiceDescription Element mandatory in both, but DVB also mandates the Scope element
_The Scope element can be added in DVB, I believe this is fine. DASH-IF does not mandate as we do not target a specific client._

PRFT MPD Element mandatory in DASH-IF but optional in DVB DASH

_In DASH-IF it is not fully mandated, you can have a legacy setup._

scoping urn to signal low latency content defined in DVB but not in DASH-IF

_Complementary. I believe it is fine._

supplemental/essential property for annotating ll adaptationset available in DVB but not in DASH-IF

_Ok for DVB, DASH-IF does not add this explicitly but implicitly._

http chunked transfer encoding mandatory in DASH-IF but not in DVB

_DASH-IF does not define the protocol_

player behavior defined in DVB but not in DASH-IF (only limited)

_This has been updated. And there is reference to DVB. We may need to have to do more once we do dash.js implementation._

requirements for encoder/packager RT behavior defined in DASH-IF but not in DVB
_This is not a requirement, but a proposal._

inband prft (file format prft) used in DASH-IF but not in DVB
_Not mandated, permitted._

It would be good consider aligning the two specifications as mentioned in the text.
There are probably more differences/inconsistencies, but these were the ones that I found initially after going through the specifications.

_I believe we are good, nothing needs to be changed._
