### ISSUE TITLE
Explain meaning of Minimum Buffer Time

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Live#5]
There is an issue on minimum buffer time that had not been sufficiently explained. Some diagram should be added.

**Comment by waqarz** [comment]
In relation to: "If a Media Segments with segment number k is delivered over a constant bitrate channel with bitrate equal to value of the @bandwidth attribute then each presentation time PT is available at the client latest at time with a delay of at most PT + MBT."

"at time with a delay of" is incomprehensible. If this is meant to imply: "... a sample with presentation time PT shall be available at the client latest by PT + MBT," then this allows media to be "available at the client" after its decode time, which will break continuous playback.
