### ISSUE TITLE
Segment duration and target latency

### ISSUE THREAD

**Issue by poolec** [Dash-Industry-Forum/Live#50]
Issue #39 does not seem to have been implemented correctly in the community review document.

That issue concluded that "Requirement is on Max Latency instead of Target Latency" but the text in 4.X.3.2 point 2d still reads:

> If the Adaptation Set contains more than one Representation for switching bitrates, then the maximum segment duration should be smaller than the anticipated client buffer size. An upper bound to the client buffer  size  is  the  target  latency. Hence,  the  maximum  segment  duration  shall  be  smaller  than  the signaled target latency. 

It should read:

> If the Adaptation Set contains more than one Representation for switching bitrates, then the maximum segment duration should be smaller than the anticipated client buffer size. An upper bound to the client buffer  size  is  **the  latency**. Hence,  the  maximum  segment  duration  shall  be  smaller  than  **any signalled MaximumLatency**. 

I'd also propose modifying 4.X.3.3, point 3a to make it clearer and give a relevant example.  Suggest changing this:

> If the target latency is set, the client when consuming in live mode, it should play the content within 500ms tolerance of the described target latency. However, the client should consider meeting the latency target also by taking into acccount knowledge of its own capabilities, the network conditions, and any relevant knowledge of past streaming performance.

to this:

> If the target latency is set, the client when consuming in live mode, it should play the content within 500ms tolerance of the described target latency. **However, the client should also take into account** knowledge of its own capabilities, the network conditions, and any relevant knowledge of past streaming performance. **For example, a client that requires a buffer size of at least one segment duration for Representation switching should not attempt to present content with a latency that doesn't allow for that, if the selected Adaptation Sets contain more than one Representation.**

**Comment by haudiobe** [comment]
(Live TF 19/07/19): Agree, if no adverse comments are received by next live call, this will be implemented.

Buffer size should be changed to buffer duration.
