### ISSUE TITLE
Avoid automatic termination due to buffering

### ISSUE THREAD

**Issue by poolec** [Dash-Industry-Forum/Live#51]
4.X.3.3 point 3b reads:
> If the max latency is set, the client when consuming in live mode, it should not exceed the described max latency even if it observes rebuffering. In this it is preferred to terminate the service.

The second sentence here is problematic.

Viewers really don't like playback stopping of its own accord during a programme that they're watching.  They would rather stop themselves if they don't like the quality they're getting (or there is excessive buffering) or plough on if they really want to see the content.

Propose that the second sentence is deleted.  It could either be left at that, or the following could be added instead:
> If the maximum latency is reached, it is preferred to continue playback by skipping ahead, remaining within the signalled maximum latency.

It's really a very similar scenario to what happens if there is insufficient bandwidth to watch the lowest representation.  This can happen for a period of time that causes lots of rebuffering but quite often the viewer can manage the situation (e.g. by shouting upstairs for their kids to stop downloading whatever they're downloading) and even if they can't, it should be the viewer's choice to give up if they consider it unwatchable.

Having a player flag the problem is fine (e.g. "We're having trouble keeping up with this live stream at the moment") but we shouldn't advocate unilaterally stopping the stream in the middle of whatever the viewer was watching.  Skipping ahead is a much better response - if it's latency critical content, that's most likely what the viewer would do anyway (e.g. reload to get back to the live edge).

**Comment by haudiobe** [comment]
(Live TF 19/07/19) generally agree that terminating is not the best option. make skip ahead as one option.

Implement accordingly unless a comment is received by next Live TF call.
