### ISSUE TITLE
Extend Community Review deadline until Sep 05 2019

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Live#53]
The MPEG 4th edition is an important component for the LL-DASH spec. It will only be ready by August 6. Hence it is proposed to extend the deadline by 30 days until Sep 5.

**Comment by wilaw** [comment]
+1

This would also allow feedback from the low latency discussions at MHV2019 to be collected.

-Will

**Comment by haudiobe** [comment]
(Live TF 2019-08-02) Agreed - extended the timeline
