### ISSUE TITLE
Representation@availabilityTimeOffset possible conflict with MPEG DASH 4th edition

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/Live#60]
In CR r3 there is a mention of `Representation@availabilityTimeOffset` attribute in section 4.X.3.2. However, `Representation@availabilityTimeOffset`  does not seem to be in DASH specification 4th edition or DASH schema. Was it supposed to be `SegmentBase@availabilityTimeOffset` or `BaseURL@availabilityTimeOffset`? 

NOTE: Representation@availabilityTimeOffset seems to be mentioned in IOP v4.3 as well. So, I opened the similar issue at the IOP repository ([link](https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/389)).

**Comment by haudiobe** [comment]
Correct needs fix.

**Comment by haudiobe** [comment]
Implemented
